import Link from "next/link";
import { ArrowUpRight, Check, Sprout, ShieldCheck, PackageCheck, Ship, FileCheck2, Handshake, Globe2, Microscope } from "lucide-react";
import { images } from "./site-data";
import { Photo, Reveal } from "./ui";
import { PageCTA, PageHero, PhotoStrip } from "./page-components";

export const informationPages = {
  about: { label:"About us", title:"Local roots.", accent:"Long-term relationships.", description:"Meet AKM Enterprises: a Karachi-based agricultural commodities exporter connecting Pakistani supply with international buyers.", seoTitle:"About AKM Enterprises | Agricultural Exporter in Karachi", seoDescription:"Learn about AKM Enterprises, a Karachi-based exporter of Pakistan-origin Natural Sesame Seeds and Yellow Corn / Maize for international buyers.", image:images.cornfield, alt:"Green corn plants beneath a summer sky" },
  origin: { label:"Our origin", title:"Sourced in Pakistan.", accent:"Exported from Karachi.", description:"A clear origin, practical local sourcing and export preparation built around your requirements.", seoTitle:"Pakistan-Origin Agricultural Commodities", seoDescription:"Explore AKM Enterprises' Pakistan sourcing focus, Karachi export base, and approach to Natural Sesame Seeds and Yellow Corn / Maize.", image:images.field, alt:"Neat rows of agricultural crops across open farmland" },
  quality: { label:"Quality", title:"Quality you can verify.", accent:"Confidence you can build on.", description:"Agreed specifications, clear communication and verification before shipment. Our quality process starts with your market.", seoTitle:"Quality & Inspection Support", seoDescription:"See how AKM Enterprises coordinates agreed specifications, samples and inspection support for sesame seeds and yellow maize exports.", image:images.sesame, alt:"Natural sesame seeds showing their texture and colour" },
  "global-reach": { label:"Global reach", title:"From our export base.", accent:"To your next market.", description:"Welcoming international importers, wholesalers, distributors and processors seeking sesame seeds and yellow maize from Pakistan.", seoTitle:"Global Agricultural Commodity Export Support", seoDescription:"AKM Enterprises supports international importers, wholesalers, distributors and processors sourcing sesame seeds and yellow maize from Pakistan.", image:images.ship, alt:"A container ship carrying cargo across the sea" },
  "export-documentation": { label:"Export & documentation", title:"The details matter.", accent:"From inquiry to shipment.", description:"Product information, packing coordination and export documentation, organized around your transaction and destination.", seoTitle:"Export Packing & Documentation Support", seoDescription:"Learn about AKM Enterprises' packing, loading and export-documentation support for Pakistan-origin sesame seeds and yellow maize.", image:images.containers, alt:"Colourful intermodal shipping containers in a freight yard" },
  faq: { label:"Frequently asked questions", title:"Good questions.", accent:"Clear answers.", description:"Practical information about products, samples, packing, inspection and international shipments.", seoTitle:"Sesame Seeds & Maize Export FAQ", seoDescription:"Answers about AKM Enterprises' Pakistan-origin sesame seeds and yellow maize, including samples, specifications, packing, inspection and shipping.", image:images.maizeHarvest, alt:"Close-up of harvested golden maize kernels" },
};
export type InformationSlug = keyof typeof informationPages;

function CheckList({items}:{items:string[]}) { return <ul className="check-list">{items.map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul>; }

function AboutContent() {
  return <>
    <section className="section container editorial-split"><Reveal><div className="eyebrow">THE COMPANY BEHIND THE COMMODITIES</div><h2>Focused products.<br/><em>Thoughtful export service.</em></h2><p>AKM Enterprises is a Pakistan-based company in Karachi, engaged in exporting agricultural commodities to international markets. Our current focus is Natural Sesame Seeds and Yellow Corn / Maize sourced from Pakistan and prepared to agreed buyer specifications.</p><p>International buyers need more than a price. They need clear specifications, consistent communication, reliable packing, inspection support and proper documentation. That understanding shapes our approach from the first inquiry to final shipment.</p><Link href="/products" className="text-link">Explore our two core products <ArrowUpRight size={18}/></Link></Reveal><figure className="editorial-photo"><Photo src={images.maizeHarvest} alt="Golden maize kernels after harvest"/><figcaption>A focused selection for international commodity buyers.</figcaption></figure></section>
    <section className="mission-band"><div className="container"><Sprout size={40} strokeWidth={1.2}/><div><div className="eyebrow light">OUR MISSION</div><h2>Connecting reliable Pakistani supply<br/>with <em>international opportunity.</em></h2><p>Through quality-focused sourcing, clear commercial communication and dependable export service.</p></div></div></section>
    <section className="section container"><div className="section-heading centered"><div className="eyebrow">OUR COMMITMENT</div><h2>Built for <em>lasting relationships.</em></h2></div><div className="commitment-grid">{[{icon:FileCheck2,title:"Clear specifications",text:"Product parameters agreed before commercial finalization."},{icon:Handshake,title:"Responsive communication",text:"Practical conversations with buyers from inquiry through shipment."},{icon:PackageCheck,title:"Flexible packing",text:"25 kg and 50 kg bags, with other options by agreement."},{icon:Microscope,title:"Inspection coordination",text:"Samples and mutually agreed inspection support when requested."},{icon:Ship,title:"Export documentation",text:"Documents coordinated for the transaction and destination."},{icon:Globe2,title:"An international outlook",text:"Working with importers, distributors, processors and traders."}].map(({icon:Icon,title,text})=><article key={title}><Icon size={27}/><h3>{title}</h3><p>{text}</p></article>)}</div><PhotoStrip items={[{src:images.sesame,alt:"Natural sesame seeds",label:"Natural Sesame Seeds"},{src:images.cornfield,alt:"Rows of growing maize",label:"Agricultural sourcing"},{src:images.containers,alt:"Export shipping containers",label:"Export coordination"}]}/></section>
  </>;
}

function OriginContent() {
  return <>
    <section className="section container editorial-split"><figure className="editorial-photo"><Photo src={images.cornfield} alt="Green leaves and rows of growing corn"/><figcaption>Agricultural imagery illustrating the commodities we source.</figcaption></figure><Reveal><div className="eyebrow">LOCAL SOURCING. CLEAR ORIGIN.</div><h2>Good trade begins<br/><em>at the source.</em></h2><p>Pakistan has a diverse agricultural base and established commodity trading networks. AKM Enterprises works with local supply channels to source Sesame Seeds and Yellow Corn / Maize for export according to agreed commercial and quality requirements.</p><h3>What Pakistan origin means for you</h3><CheckList items={["Products sourced within Pakistan","Export preparation to agreed buyer specifications","Packing coordinated for containerized international shipment","Documentation based on your transaction and destination"]}/></Reveal></section>
    <section className="soft-section section"><div className="container editorial-split"><div><div className="eyebrow">KARACHI / OUR EXPORT GATEWAY</div><h2>Local access.<br/><em>International connections.</em></h2><p>Our Karachi location gives us practical access to Pakistan’s commercial and export infrastructure, supporting containerized shipments to international buyers.</p><p>Shipment plans are discussed around the destination port, packing format, product availability and commercial terms.</p><Link href="/global-reach" className="text-link">Discover our international buyer support <ArrowUpRight size={18}/></Link></div><figure className="editorial-photo"><Photo src={images.containers} alt="Rows of stacked containers ready for freight transport"/><figcaption>Representative container logistics imagery.</figcaption></figure></div></section>
    <section className="container section season-note"><Sprout size={35}/><div><div className="eyebrow">WORKING WITH THE SEASON</div><h2>Ask about the <em>current crop.</em></h2><p>Crop availability and final specifications can vary by season. Request the latest availability, crop information and product photographs before placing an order.</p><Link href="/contact" className="text-link">Request current availability <ArrowUpRight size={18}/></Link></div></section>
  </>;
}

function QualityContent() {
  const process=["Confirm your specifications and intended market","Source product matching the agreed commercial parameters","Clean, dry and sort the commodity as applicable","Review packing requirements before loading","Share photographs, samples or inspection information on request","Coordinate third-party inspection when mutually agreed","Prepare shipment and export documentation"];
  return <>
    <section className="section container editorial-split"><Reveal><div className="eyebrow">OUR APPROACH</div><h2>Agreed requirements.<br/><em>Visible checks.</em></h2><p>We confirm product quality requirements with you before commercial finalization. Samples, product photographs and inspection information help you assess the available product against your requirements.</p><p>Third-party inspection can be coordinated when requested and mutually agreed. Inspection scope and cost are confirmed before shipment.</p><Link href="/contact" className="text-link">Discuss your quality requirements <ArrowUpRight size={18}/></Link></Reveal><figure className="editorial-photo"><Photo src={images.inspection} alt="Laboratory professional examining a sample through a microscope"/><figcaption>Illustrative inspection imagery. Third-party inspection is arranged by agreement.</figcaption></figure></section>
    <section className="soft-section section"><div className="container quality-grid"><div><div className="eyebrow">FROM REQUIREMENT TO READINESS</div><h2>Our quality<br/><em>process.</em></h2><Photo src={images.sesame} alt="Natural sesame seed sample in detail" className="quality-detail-image"/></div><ol className="numbered-process">{process.map((step,i)=><li key={step}><span>0{i+1}</span><p>{step}</p></li>)}</ol></div></section>
    <section className="section container"><div className="section-heading"><div className="eyebrow">PRODUCT PARAMETERS</div><h2>Start with the <em>specifications.</em></h2></div><div className="spec-summary-grid"><Link href="/products/sesame-seeds"><Photo src={images.sesame} alt="Pale sesame seeds"/><div><h3>Natural Sesame Seeds</h3><p>99.95% minimum purity · 6% maximum moisture</p><span className="text-link">See all specifications <ArrowUpRight size={17}/></span></div></Link><Link href="/products/yellow-maize"><Photo src={images.maizeHarvest} alt="Harvested yellow maize"/><div><h3>Yellow Corn / Maize</h3><p>14% maximum moisture · 1% maximum foreign matter</p><span className="text-link">See all specifications <ArrowUpRight size={17}/></span></div></Link></div><div className="content-note"><ShieldCheck size={26}/><p>Agricultural commodities are natural products. Final quality parameters, inspection standards, tolerances and destination-country limits must be confirmed in the sales contract or proforma invoice before shipment.</p></div></section>
  </>;
}

function GlobalContent() {
  return <>
    <section className="section container editorial-split"><div><div className="eyebrow">INTERNATIONAL INQUIRIES WELCOME</div><h2>Your market.<br/><em>Our product focus.</em></h2><p>We welcome inquiries from businesses seeking Natural Sesame Seeds and Yellow Corn / Maize from Pakistan. Whether you need an ingredient for processing or a commodity for distribution, share your intended use and required specifications.</p><CheckList items={["Importers and commodity traders","Wholesalers and distributors","Food and industrial processors, subject to grade","Feed and grain distributors"]}/></div><figure className="editorial-photo"><Photo src={images.ship} alt="Aerial view of a container ship crossing open water"/><figcaption>International shipment arrangements depend on destination and availability.</figcaption></figure></section>
    <section className="soft-section section"><div className="container"><div className="section-heading centered"><div className="eyebrow">COMMERCIAL TERMS</div><h2>Let’s discuss <em>your shipment.</em></h2></div><div className="terms-grid">{["FOB","CFR","CIF"].map(term=><article key={term}><Ship size={27}/><h3>{term}</h3><p>Available for discussion according to your destination, shipment requirements and commercial agreement.</p></article>)}</div><p className="fineprint centered">Final freight and shipment arrangements depend on the port, carrier availability, container type and prevailing logistics conditions.</p></div></section>
    <section className="section container editorial-split"><figure className="editorial-photo"><Photo src={images.containers} alt="Stacked intermodal containers in a freight yard"/><figcaption>Preparing a clear inquiry helps us discuss an appropriate commercial offer.</figcaption></figure><div><div className="eyebrow">A BETTER INQUIRY. A CLEARER OFFER.</div><h2>Tell us <em>what you need.</em></h2><CheckList items={["Product and required quantity","Destination country and port","Preferred Incoterm, if known","Required quality specification","Packing format and target shipment period","Inspection or certification requirements"]}/><Link href="/contact" className="button">Prepare your inquiry <ArrowUpRight size={18}/></Link></div></section>
  </>;
}

function ExportContent() {
  return <>
    <section className="section container editorial-split"><div><div className="eyebrow">PACKING THAT FITS YOUR REQUIREMENTS</div><h2>Practical formats.<br/><em>Agreed together.</em></h2><p>We coordinate packing to match the commodity, quantity and buyer requirements. Buyer-specific formats are subject to feasibility and commercial agreement.</p><CheckList items={["25 kg PP bags","50 kg PP bags","Bulk maize where commercially suitable","Buyer-specific packing by agreement"]}/><Link href="/contact" className="text-link">Discuss your packing requirements <ArrowUpRight size={18}/></Link></div><figure className="editorial-photo"><Photo src={images.containers} alt="Stacked shipping containers at a logistics facility"/><figcaption>Containerized supply with packing and loading agreed before shipment.</figcaption></figure></section>
    <section className="soft-section section"><div className="container"><div className="section-heading"><div className="eyebrow">INDICATIVE CONTAINER LOADING</div><h2>Plan around <em>the product.</em></h2></div><div className="loading-cards"><article><Photo src={images.sesame} alt="Natural sesame seeds"/><div><h3>Natural Sesame Seeds</h3><strong>18–20 MT</strong><span>per 20ft container, approximately</span></div></article><article><Photo src={images.maizeHarvest} alt="Golden maize kernels"/><div><h3>Yellow Corn / Maize</h3><strong>22–24 MT</strong><span>per 20ft container, approximately</span></div></article></div><p className="fineprint">Actual loading varies with packing format, bag dimensions, product density, container payload limits and shipping-line requirements.</p></div></section>
    <section className="section container editorial-split"><div><div className="eyebrow">DOCUMENTATION SUPPORT</div><h2>Right details.<br/><em>Before confirmation.</em></h2><p>Required documents are discussed at quotation stage. Depending on the transaction and destination, these may include commercial, shipping, origin and inspection documents, alongside other requirements from the buyer, carrier, bank or importing authority.</p><p>Advise the exact certificate or inspection requirement before order confirmation so the scope can be discussed and agreed.</p><Link href="/contact" className="button">Discuss export documentation <ArrowUpRight size={18}/></Link></div><ol className="numbered-process">{["Share your destination and document requirements","Confirm product specifications and packing","Agree inspection scope where required","Coordinate shipment and transaction documents","Review agreed details before shipment"].map((text,i)=><li key={text}><span>0{i+1}</span><p>{text}</p></li>)}</ol></section>
  </>;
}

const faqGroups = [
  { title:"Products & samples", items:[
    ["Where are your products sourced?","Our Sesame Seeds and Yellow Corn / Maize are sourced from Pakistan through local agricultural and commodity supply channels."],
    ["Can you provide product samples?","Yes. Samples can be discussed and arranged upon request, subject to availability, courier arrangements and commercial requirements."],
    ["Can specifications be customized?","Final specifications can be discussed according to buyer requirements, crop availability and destination-country regulations."],
  ]},
  { title:"Packing & shipping", items:[
    ["What packaging do you offer?","Standard options include 25 kg and 50 kg PP bags. Buyer-specific packing can also be discussed. Maize may be supplied in bulk where commercially suitable."],
    ["How much can be loaded in a 20ft container?","Indicatively, Natural Sesame Seeds are approximately 18–20 MT and Yellow Corn / Maize approximately 22–24 MT. Actual loading varies with packing, product density, payload limits and shipping-line requirements."],
    ["Which Incoterms can you quote?","FOB, CFR or CIF can be discussed depending on buyer requirements, destination and prevailing freight conditions."],
  ]},
  { title:"Inspection & ordering", items:[
    ["Can you arrange third-party inspection?","Third-party inspection can be coordinated when requested and mutually agreed. Inspection scope and cost should be confirmed before shipment."],
    ["Do you provide export documentation?","Required export and shipment documentation can be coordinated according to the transaction and destination-country requirements. Advise any mandatory certificates before order confirmation."],
    ["How can I get a quotation?","Share the product, quantity, destination port, specification, packing requirement and preferred Incoterm. Use our Contact page to prepare an inquiry, open it in your email app and send it to contact@akmenterprises.info."],
  ]},
];

function FAQContent() {
  return <section className="section container faq-page-grid"><aside><div className="eyebrow">BUYER INFORMATION</div><h2>Before <em>we begin.</em></h2><p>Find the details that help you plan your next purchase.</p><nav aria-label="FAQ topics">{faqGroups.map((group,i)=><a href={`#topic-${i}`} key={group.title}>{group.title}<ArrowUpRight size={16}/></a>)}</nav><Photo src={images.cornfield} alt="Growing maize in an agricultural field"/><Link href="/contact" className="button">Ask our export team <ArrowUpRight size={17}/></Link></aside><div>{faqGroups.map((group,i)=><section className="faq-topic" id={`topic-${i}`} key={group.title}><h2>{group.title}</h2><div className="faqs">{group.items.map(([q,a])=><details key={q}><summary>{q}<span className="faq-plus" aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>)}</div></section>;
}

const content = {about:AboutContent,origin:OriginContent,quality:QualityContent,"global-reach":GlobalContent,"export-documentation":ExportContent,faq:FAQContent};
export function InformationPage({slug}:{slug:InformationSlug}) {
  const Content = content[slug];
  return <main id="main-content"><PageHero {...informationPages[slug]} compact={slug==="faq"}/><Content/><PageCTA/></main>;
}
