import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, ArrowLeft, Check, Leaf, FileCheck2 } from "lucide-react";
import { products } from "../../site-data";
import { Photo } from "../../ui";
export function generateStaticParams(){return products.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=products.find(p=>p.slug===slug);return {title:p?`${p.name} Exporter Pakistan`:"Product not found",description:p?.description};}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const product=products.find(p=>p.slug===slug);if(!product)notFound();
  return <main id="main-content"><section className="product-page-hero section"><div className="container"><Link href="/#products" className="text-link back-link"><ArrowLeft size={16}/> All products</Link><div className="product-page-grid"><div><div className="eyebrow"><Leaf size={15}/> PAKISTAN ORIGIN · OUR SELECTION</div><h1>{product.name}<em>from Pakistan.</em></h1><p>{product.description}</p><Link href="/#quote" className="button">Request a commercial quote <ArrowUpRight size={18}/></Link></div><Photo src={product.image} alt={product.imageAlt} priority/></div></div></section><section className="section container specifications-grid"><div><div className="eyebrow">PRODUCT AT A GLANCE</div><h2>Clear specifications.<br/><em>Confident decisions.</em></h2><table className="spec-table"><caption>Indicative specifications for {product.name}</caption><thead><tr><th>Parameter</th><th>Specification</th></tr></thead><tbody>{product.specs.map(([key,value])=><tr key={key}><th scope="row">{key}</th><td>{value}</td></tr>)}</tbody></table><p className="fineprint">Final parameters, tolerances, inspection standards and destination-country limits must be confirmed in the sales contract or proforma invoice. Container loading is approximate and depends on packing and payload limits.</p></div><aside className="product-sidebar"><div className="sidebar-card"><h3>{slug==="sesame-seeds"?"Applications":"Suitable buyers"}</h3>{product.uses.map(use=><p className="use-item" key={use}><Check size={17}/>{use}</p>)}</div><div className="sidebar-card green"><FileCheck2 size={30}/><h3>A closer look?</h3><p>Ask for samples, current photographs, detailed specifications, packing information and inspection reports where arranged.</p><Link href="/#quote" className="button gold">Ask for specifications <ArrowUpRight size={17}/></Link></div></aside></section><div className="container product-crosslink"><span>Explore our other product</span>{products.filter(p=>p.slug!==slug).map(p=><Link href={`/products/${p.slug}`} key={p.slug}>{p.name}<ArrowUpRight/></Link>)}</div></main>;
}
